"""
AIRCP User Configuration

Loads user-specific config from ~/.aircp/config.toml
Provides sensible defaults for all configurable values.

Precedence: CLI args > env vars > config file > defaults
"""
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
_DEFAULTS = {
    "user": "@operator",
    "daemon_host": "localhost",
    "daemon_port": 5555,
    "workspace": str(Path.home() / "projects"),
    "forum_url": "https://aircp.dev",
    "domain_id": 219,
}

# ---------------------------------------------------------------------------
# Config singleton
# ---------------------------------------------------------------------------
_config = None

CONFIG_DIR = Path.home() / ".aircp"
CONFIG_FILE = CONFIG_DIR / "config.toml"


def _load_toml(path: Path) -> dict:
    """Load TOML file, return empty dict if missing or broken."""
    if not path.exists():
        return {}
    try:
        import tomllib
        with open(path, "rb") as f:
            return tomllib.load(f)
    except Exception:
        return {}


def load() -> dict:
    """Load user config (cached singleton)."""
    global _config
    if _config is not None:
        return _config

    raw = _load_toml(CONFIG_FILE)

    _config = {
        "user": (
            os.environ.get("AIRCP_USER")
            or raw.get("user")
            or _DEFAULTS["user"]
        ),
        "daemon_host": (
            os.environ.get("AIRCP_HOST")
            or raw.get("daemon_host")
            or _DEFAULTS["daemon_host"]
        ),
        "daemon_port": int(
            os.environ.get("AIRCP_PORT")
            or raw.get("daemon_port")
            or _DEFAULTS["daemon_port"]
        ),
        "workspace": (
            os.environ.get("AIRCP_WORKSPACE")
            or raw.get("workspace")
            or _DEFAULTS["workspace"]
        ),
        "forum_url": (
            os.environ.get("FORUM_API_URL")
            or raw.get("forum_url")
            or _DEFAULTS["forum_url"]
        ),
        "domain_id": int(
            os.environ.get("AIRCP_DOMAIN_ID")
            or raw.get("domain_id")
            or _DEFAULTS["domain_id"]
        ),
    }
    return _config


def get(key: str, fallback=None):
    """Get a single config value."""
    return load().get(key, fallback)


# ---------------------------------------------------------------------------
# Convenience accessors (avoid load() boilerplate everywhere)
# ---------------------------------------------------------------------------

def user() -> str:
    return get("user")


def daemon_url() -> str:
    cfg = load()
    return f"http://{cfg['daemon_host']}:{cfg['daemon_port']}"


def human_ids() -> set:
    """Set of identifiers considered human (for watchdog, brainstorm, etc.)."""
    u = user()
    base = u.lstrip("@")
    return {u, f"@{base}", base, "@human"}


def is_configured() -> bool:
    """True if user has run 'aircp setup'."""
    return CONFIG_FILE.exists()


# ---------------------------------------------------------------------------
# Setup wizard
# ---------------------------------------------------------------------------

def run_setup(non_interactive: bool = False, defaults: dict = None):
    """Interactive first-time setup. Writes ~/.aircp/config.toml."""
    defaults = defaults or {}

    print()
    print("  aIRCp - First-Time Setup")
    print("  " + "-" * 30)
    print()

    if non_interactive:
        username = defaults.get("user", _DEFAULTS["user"])
        workspace = defaults.get("workspace", _DEFAULTS["workspace"])
        port = defaults.get("daemon_port", _DEFAULTS["daemon_port"])
        forum = defaults.get("forum_url", _DEFAULTS["forum_url"])
    else:
        username = input(f"  Your handle [@operator]: ").strip() or _DEFAULTS["user"]
        if not username.startswith("@"):
            username = f"@{username}"

        workspace = input(f"  Workspace path [~/projects]: ").strip()
        workspace = workspace or _DEFAULTS["workspace"]
        workspace = str(Path(workspace).expanduser())

        port_str = input(f"  Daemon port [5555]: ").strip()
        port = int(port_str) if port_str else _DEFAULTS["daemon_port"]

        forum = input(f"  Forum URL [https://aircp.dev]: ").strip()
        forum = forum or _DEFAULTS["forum_url"]

    # Write config
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    content = f'''# aIRCp User Configuration
# Generated by: aircp setup
# Edit this file to change your settings.

# Your identity (used as default sender in CLI and daemon)
user = "{username}"

# Daemon connection
daemon_host = "localhost"
daemon_port = {port}

# Workspace root (where your projects live)
workspace = "{workspace}"

# Forum URL
forum_url = "{forum}"

# HDDS DDS domain ID (do not change unless you know what you're doing)
domain_id = 219
'''

    CONFIG_FILE.write_text(content)

    print()
    print(f"  Config written to {CONFIG_FILE}")
    print(f"  Identity: {username}")
    print(f"  Daemon:   localhost:{port}")
    print(f"  Workspace: {workspace}")
    print()
    print("  Run 'aircp-daemon start' to begin.")
    print()

    # Reset cached config
    global _config
    _config = None
